name: 'Trial Onboarding Comments Action'
description: 'Creates a process around to enable early-access programs for trials'
inputs:
  github-token:  # id of input
    description: 'Token to use'
    required: true
  onboarding-comment:  
    description: 'Comment for onboarding'
    required: true
runs:
  using: 'node12'
  main: 'index.js'